CustomizedFormulation.create!([
])
Formulation.create!([
  {name: "Acne: mild inflammatory"},
  {name: "Acne: inflammatory"},
  {name: "Acne: comedonal"},
  {name: "Rhytides/poikiloderma (sensitive)"},
  {name: "Rosacea/baseline erythema"},
  {name: "Lentigines 1"},
  {name: "Lentigines 2"},
  {name: "Melasma 1"},
  {name: "Melasma 2"},
  {name: "Apple formula"},
  {name: "Peach formula"},
  {name: "Orange formula"},
  {name: "Melasma 3"},
  {name: "Anti-aging 1"},
  {name: "Anti-aging 2"},
  {name: "Seborrhea 1"},
  {name: "Pseudofolliculitis"},
  {name: "Pityriasis alba"},
  {name: "Acne: pregnant"},
  {name: "PIH: actively inflamed"},
  {name: "Xerosis/Eczema"},
  {name: "Acne: aggressive"},
  {name: "Anti-oxidant"},
  {name: "Anti-aging 3"},
  {name: "Anti-aging 4"},
  {name: "Pear formula"},
  {name: "Grape formula"},
  {name: "Melasma 4"},
  {name: "Rosacea"},
  {name: "Keratosis pilaris"},
  {name: "Melasma 5"},
  {name: "Seborrhea 2"}
])
FormulationIngredient.create!([
  {formulation_id: 1, ingredient_id: 7, percentage: "10.0"},
  {formulation_id: 1, ingredient_id: 25, percentage: "5.0"},
  {formulation_id: 1, ingredient_id: 20, percentage: "2.0"},
  {formulation_id: 1, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 2, ingredient_id: 8, percentage: "4.0"},
  {formulation_id: 2, ingredient_id: 20, percentage: "4.0"},
  {formulation_id: 2, ingredient_id: 10, percentage: "1.0"},
  {formulation_id: 2, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 3, ingredient_id: 14, percentage: "2.0"},
  {formulation_id: 3, ingredient_id: 2, percentage: "2.0"},
  {formulation_id: 3, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 3, ingredient_id: 1, percentage: "1.0"},
  {formulation_id: 3, ingredient_id: 26, percentage: "0.05"},
  {formulation_id: 4, ingredient_id: 20, percentage: "4.0"},
  {formulation_id: 4, ingredient_id: 3, percentage: "1.0"},
  {formulation_id: 4, ingredient_id: 13, percentage: "1.0"},
  {formulation_id: 4, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 5, ingredient_id: 25, percentage: "5.0"},
  {formulation_id: 5, ingredient_id: 20, percentage: "4.0"},
  {formulation_id: 5, ingredient_id: 19, percentage: "1.0"},
  {formulation_id: 5, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 6, ingredient_id: 17, percentage: "5.0"},
  {formulation_id: 6, ingredient_id: 4, percentage: "2.0"},
  {formulation_id: 6, ingredient_id: 2, percentage: "2.0"},
  {formulation_id: 6, ingredient_id: 3, percentage: "1.0"},
  {formulation_id: 6, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 6, ingredient_id: 26, percentage: "0.05"},
  {formulation_id: 7, ingredient_id: 15, percentage: "4.0"},
  {formulation_id: 7, ingredient_id: 26, percentage: "0.1"},
  {formulation_id: 7, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 7, ingredient_id: 14, percentage: "1.0"},
  {formulation_id: 7, ingredient_id: 31, percentage: "2.0"},
  {formulation_id: 8, ingredient_id: 17, percentage: "4.0"},
  {formulation_id: 8, ingredient_id: 15, percentage: "4.0"},
  {formulation_id: 8, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 8, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 9, ingredient_id: 7, percentage: "10.0"},
  {formulation_id: 9, ingredient_id: 17, percentage: "4.0"},
  {formulation_id: 9, ingredient_id: 13, percentage: "2.0"},
  {formulation_id: 9, ingredient_id: 3, percentage: "1.0"},
  {formulation_id: 10, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 10, ingredient_id: 17, percentage: "3.0"},
  {formulation_id: 10, ingredient_id: 15, percentage: "2.0"},
  {formulation_id: 10, ingredient_id: 5, percentage: "2.0"},
  {formulation_id: 10, ingredient_id: 6, percentage: "2.0"},
  {formulation_id: 10, ingredient_id: 14, percentage: "2.0"},
  {formulation_id: 10, ingredient_id: 1, percentage: "1.0"},
  {formulation_id: 10, ingredient_id: 16, percentage: "0.5"},
  {formulation_id: 10, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 11, ingredient_id: 6, percentage: "5.0"},
  {formulation_id: 11, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 11, ingredient_id: 14, percentage: "2.0"},
  {formulation_id: 11, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 12, ingredient_id: 25, percentage: "5.0"},
  {formulation_id: 12, ingredient_id: 7, percentage: "5.0"},
  {formulation_id: 12, ingredient_id: 6, percentage: "5.0"},
  {formulation_id: 12, ingredient_id: 10, percentage: "1.0"},
  {formulation_id: 12, ingredient_id: 14, percentage: "1.0"},
  {formulation_id: 12, ingredient_id: 26, percentage: "0.05"},
  {formulation_id: 13, ingredient_id: 15, percentage: "8.0"},
  {formulation_id: 13, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 13, ingredient_id: 16, percentage: "2.0"},
  {formulation_id: 13, ingredient_id: 17, percentage: "4.0"},
  {formulation_id: 14, ingredient_id: 29, percentage: "0.5"},
  {formulation_id: 14, ingredient_id: 30, percentage: "3.0"},
  {formulation_id: 14, ingredient_id: 38, percentage: "0.5"},
  {formulation_id: 14, ingredient_id: 31, percentage: "2.0"},
  {formulation_id: 14, ingredient_id: 28, percentage: "3.0"},
  {formulation_id: 14, ingredient_id: 32, percentage: "1.0"},
  {formulation_id: 14, ingredient_id: 33, percentage: "1.0"},
  {formulation_id: 15, ingredient_id: 29, percentage: "0.5"},
  {formulation_id: 15, ingredient_id: 38, percentage: "0.5"},
  {formulation_id: 15, ingredient_id: 31, percentage: "2.0"},
  {formulation_id: 15, ingredient_id: 28, percentage: "3.0"},
  {formulation_id: 15, ingredient_id: 34, percentage: "0.3"},
  {formulation_id: 15, ingredient_id: 32, percentage: "1.0"},
  {formulation_id: 15, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 15, ingredient_id: 35, percentage: "0.01"},
  {formulation_id: 16, ingredient_id: 25, percentage: "8.0"},
  {formulation_id: 16, ingredient_id: 21, percentage: "3.0"},
  {formulation_id: 16, ingredient_id: 20, percentage: "2.0"},
  {formulation_id: 16, ingredient_id: 23, percentage: "2.0"},
  {formulation_id: 16, ingredient_id: 13, percentage: "1.0"},
  {formulation_id: 16, ingredient_id: 27, percentage: "0.1"},
  {formulation_id: 17, ingredient_id: 2, percentage: "2.0"},
  {formulation_id: 17, ingredient_id: 3, percentage: "2.0"},
  {formulation_id: 17, ingredient_id: 16, percentage: "1.5"},
  {formulation_id: 17, ingredient_id: 10, percentage: "1.0"},
  {formulation_id: 17, ingredient_id: 26, percentage: "0.05"},
  {formulation_id: 18, ingredient_id: 36, percentage: "3.0"},
  {formulation_id: 18, ingredient_id: 3, percentage: "2.0"},
  {formulation_id: 18, ingredient_id: 31, percentage: "2.0"},
  {formulation_id: 18, ingredient_id: 13, percentage: "2.0"},
  {formulation_id: 18, ingredient_id: 27, percentage: "0.1"},
  {formulation_id: 18, ingredient_id: 16, percentage: "2.0"},
  {formulation_id: 18, ingredient_id: 29, percentage: "0.5"},
  {formulation_id: 19, ingredient_id: 7, percentage: "10.0"},
  {formulation_id: 19, ingredient_id: 20, percentage: "2.0"},
  {formulation_id: 19, ingredient_id: 19, percentage: "0.75"},
  {formulation_id: 20, ingredient_id: 39, percentage: "0.05"},
  {formulation_id: 20, ingredient_id: 15, percentage: "6.0"},
  {formulation_id: 20, ingredient_id: 32, percentage: "1.0"},
  {formulation_id: 20, ingredient_id: 3, percentage: "2.0"},
  {formulation_id: 20, ingredient_id: 13, percentage: "2.0"},
  {formulation_id: 21, ingredient_id: 27, percentage: "0.1"},
  {formulation_id: 21, ingredient_id: 16, percentage: "2.0"},
  {formulation_id: 21, ingredient_id: 14, percentage: "2.0"},
  {formulation_id: 21, ingredient_id: 28, percentage: "3.0"},
  {formulation_id: 21, ingredient_id: 2, percentage: "2.0"},
  {formulation_id: 21, ingredient_id: 1, percentage: "2.0"},
  {formulation_id: 22, ingredient_id: 25, percentage: "5.0"},
  {formulation_id: 22, ingredient_id: 7, percentage: "5.0"},
  {formulation_id: 22, ingredient_id: 10, percentage: "1.0"},
  {formulation_id: 22, ingredient_id: 14, percentage: "1.0"},
  {formulation_id: 22, ingredient_id: 26, percentage: "0.1"},
  {formulation_id: 22, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 23, ingredient_id: 36, percentage: "3.0"},
  {formulation_id: 23, ingredient_id: 3, percentage: "2.0"},
  {formulation_id: 23, ingredient_id: 32, percentage: "1.0"},
  {formulation_id: 23, ingredient_id: 13, percentage: "2.0"},
  {formulation_id: 23, ingredient_id: 21, percentage: "3.0"},
  {formulation_id: 23, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 24, ingredient_id: 29, percentage: "0.5"},
  {formulation_id: 24, ingredient_id: 30, percentage: "3.0"},
  {formulation_id: 24, ingredient_id: 31, percentage: "2.0"},
  {formulation_id: 24, ingredient_id: 28, percentage: "3.0"},
  {formulation_id: 24, ingredient_id: 32, percentage: "1.0"},
  {formulation_id: 24, ingredient_id: 33, percentage: "1.0"},
  {formulation_id: 24, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 24, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 25, ingredient_id: 29, percentage: "0.5"},
  {formulation_id: 25, ingredient_id: 22, percentage: "2.0"},
  {formulation_id: 25, ingredient_id: 31, percentage: "2.0"},
  {formulation_id: 25, ingredient_id: 28, percentage: "3.0"},
  {formulation_id: 25, ingredient_id: 34, percentage: "0.3"},
  {formulation_id: 25, ingredient_id: 32, percentage: "1.0"},
  {formulation_id: 25, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 25, ingredient_id: 35, percentage: "0.01"},
  {formulation_id: 25, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 26, ingredient_id: 13, percentage: "1.0"},
  {formulation_id: 26, ingredient_id: 20, percentage: "4.0"},
  {formulation_id: 26, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 26, ingredient_id: 3, percentage: "1.0"},
  {formulation_id: 27, ingredient_id: 7, percentage: "10.0"},
  {formulation_id: 27, ingredient_id: 17, percentage: "4.0"},
  {formulation_id: 27, ingredient_id: 13, percentage: "2.0"},
  {formulation_id: 27, ingredient_id: 3, percentage: "1.0"},
  {formulation_id: 27, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 28, ingredient_id: 15, percentage: "8.0"},
  {formulation_id: 28, ingredient_id: 26, percentage: "0.03"},
  {formulation_id: 28, ingredient_id: 16, percentage: "2.0"},
  {formulation_id: 28, ingredient_id: 17, percentage: "4.0"},
  {formulation_id: 28, ingredient_id: 36, percentage: "3.0"},
  {formulation_id: 29, ingredient_id: 19, percentage: "1.0"},
  {formulation_id: 29, ingredient_id: 20, percentage: "4.0"},
  {formulation_id: 29, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 29, ingredient_id: 7, percentage: "5.0"},
  {formulation_id: 30, ingredient_id: 2, percentage: "1.0"},
  {formulation_id: 30, ingredient_id: 12, percentage: "6.0"},
  {formulation_id: 30, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 30, ingredient_id: 14, percentage: "2.0"},
  {formulation_id: 30, ingredient_id: 1, percentage: "1.0"},
  {formulation_id: 31, ingredient_id: 15, percentage: "4.0"},
  {formulation_id: 31, ingredient_id: 16, percentage: "1.0"},
  {formulation_id: 31, ingredient_id: 17, percentage: "4.0"},
  {formulation_id: 31, ingredient_id: 36, percentage: "1.0"},
  {formulation_id: 31, ingredient_id: 12, percentage: "5.0"},
  {formulation_id: 32, ingredient_id: 23, percentage: "2.0"},
  {formulation_id: 32, ingredient_id: 20, percentage: "3.0"},
  {formulation_id: 32, ingredient_id: 37, percentage: "2.0"},
  {formulation_id: 32, ingredient_id: 13, percentage: "1.0"},
  {formulation_id: 32, ingredient_id: 27, percentage: "0.1"}
])
Ingredient.create!([
  {id: 1, name: "Allantoin", minimum_percentage: "1.0", maximum_percentage: "2.0", description: "Helps skin hydration and barrier function.", classes: ["Humectants"]},
  {id: 2, name: "Aloe", minimum_percentage: "1.0", maximum_percentage: "2.0", description: "Reduces skin irritation and burn treatment.", classes: ["Anti-Inflammatories"]},
  {id: 36, name: "Alpha Lipoic Acid", minimum_percentage: "1.0", maximum_percentage: "3.0", description: "An essential acid for cell metabolism and a potent anti-oxidant.", classes: ["Pigmentary Regulators", "Anti-Oxidants"]},
  {id: 3, name: "Alpha-Tocopherol (Vitamin E Acetate)", minimum_percentage: "1.0", maximum_percentage: "2.0", description: "A natural antioxidant and anti inflammatory.", classes: ["Anti-Oxidants"]},
  {id: 4, name: "Arbutin", minimum_percentage: "2.0", maximum_percentage: "4.0", description: "Naturally extracted from the Bearberry plant, helps prevent the formation of melanin and evens skin tone.", classes: ["Pigmentary Regulators"]},
  {id: 5, name: "Arnica", minimum_percentage: "2.0", maximum_percentage: "5.0", description: "Plant extract that helps to prevent blood vessel leakage / undereye darkening.", classes: ["Anti-Ecchymotic"]},
  {id: 6, name: "Ascorbic Acid", minimum_percentage: "2.0", maximum_percentage: "15.0", description: "Vitamin C, helps collagen synthesis, pigment evening, and stabilizing other ingredients.", classes: ["Pigmentary Regulators", "Anti-Oxidants"]},
  {id: 31, name: "Ascorbyl Palmitate", minimum_percentage: "0.5", maximum_percentage: "2.0", description: "Vitamin C, helps collagen synthesis, pigment evening, and stabilizing other ingredients.", classes: ["Anti-Oxidants"]},
  {id: 7, name: "Azelaic Acid", minimum_percentage: "5.0", maximum_percentage: "15.0", description: "Naturally produced by yeast. Reduces bacteria on the skin and inflammation, and regulates pigmentation.", classes: ["Anti-Inflammatories", "Pigmentary Regulators"]},
  {id: 8, name: "Benzoyl Peroxide", minimum_percentage: "2.0", maximum_percentage: "5.0", description: "Behaves as an antimicrobial without inducing antibiotic resistance.", classes: ["Anti-Microbials"]},
  {id: 29, name: "Bisabolol", minimum_percentage: "0.25", maximum_percentage: "1.0", description: "Derived from chamomile and sage, it assists the penetration of other ingredients and acts as an anti-inflammatory.", classes: ["Delivery Enhancers", "Anti-Inflammatories"]},
  {id: 9, name: "Caffeine", minimum_percentage: "0.5", maximum_percentage: "2.0", description: "Quickly penetrates skin and reduces swelling; it is also an anti-oxidant.", classes: ["Anti-Inflammatory", "Vasoconstrictors"]},
  {id: 30, name: "Chrysin", minimum_percentage: "1.0", maximum_percentage: "3.0", description: "Derived from passion flower, this flavonoid has potent anti-oxidant and anti-cancer activity.", classes: ["Anti-Oxidants", "Anti-Carcinogens"]},
  {id: 10, name: "Clindamycin", minimum_percentage: "0.5", maximum_percentage: "1.0", description: "An antibiotic to stop growth of acne-causing bacteria like P. acnes and S. aureus.", classes: ["Antibiotics"]},
  {id: 32, name: "Coenzyme Q-10", minimum_percentage: "0.5", maximum_percentage: "2.0", description: "An essential component of the body's metabolism, it helps the skin overcome injury and UV damage.", classes: ["Anti-Oxidants"]},
  {id: 11, name: "Dimethicone", minimum_percentage: "0.0", maximum_percentage: "10.0", description: "Excellent for maintaining skin barrier function.", classes: ["Barriers"]},
  {id: 35, name: "Estradiol", minimum_percentage: "0.01", maximum_percentage: "0.02", description: "A potent form of estrogen, which increases collagen, thus maintaining skin firmness and preventing wrinkles.", classes: ["Hormonal Modulators"]},
  {id: 34, name: "Estriol", minimum_percentage: "0.1", maximum_percentage: "0.5", description: "A mild form of estrogen, best known for maintaining the \u0089ÛÏpregnancy glow\u0089Û\u009D.", classes: ["Hormonal Modulators"]},
  {id: 12, name: "Glycolic Acid", minimum_percentage: "5.0", maximum_percentage: "10.0", description: "Derived from sugar cane, this alpha-hydroxy acid brightens skin without causing peeling at low concentrations.", classes: ["Keratolytics", "Pigmentary Regulators"]},
  {id: 13, name: "Green Tea Extract", minimum_percentage: "1.0", maximum_percentage: "2.0", description: "Derived from Camellia sinensis, rich in antioxidant as well as xanthines (molecules that promote circulation).", classes: ["Anti-Oxidants"]},
  {id: 14, name: "Hyaluronic Acid", minimum_percentage: "0.5", maximum_percentage: "2.0", description: "The most important agent for skin fullness and hydration.", classes: ["Humectants"]},
  {id: 16, name: "Hydrocortisone", minimum_percentage: "0.5", maximum_percentage: "2.5", description: "A mild anti-inflammatory steroid.", classes: ["Steroids"]},
  {id: 15, name: "Hydroquinone", minimum_percentage: "2.0", maximum_percentage: "8.0", description: "Naturally found in Bearberry plants, greatly improves hyperpigmentation.", classes: ["Pigmentary Regulators"]},
  {id: 40, name: "Ivermectin", minimum_percentage: "0.5", maximum_percentage: "1.0", description: "An anti-parasitic compound that targets Demodex around the hair follicles, reducing inflammation.", classes: ["Anti-Parasitic"]},
  {id: 37, name: "Ketoconazole", minimum_percentage: "1.0", maximum_percentage: "3.0", description: "An anti-fungal that targets nearly all of the problematic fungus on the skin.", classes: ["Anti-Fungal", "Anti-Inflammatories"]},
  {id: 17, name: "Kojic Acid", minimum_percentage: "2.0", maximum_percentage: "5.0", description: "A product of sake formation, it prevents oxidative darkening.", classes: ["Keratolytics", "Pigmentary Regulators"]},
  {id: 18, name: "Lactic Acid", minimum_percentage: "5.0", maximum_percentage: "10.0", description: "Alpha Hydroxy Acid (AHA) extracted from milk that helps exfoliate dead skin.", classes: ["Humectants"]},
  {id: 19, name: "Metronidazole", minimum_percentage: "0.5", maximum_percentage: "1.0", description: "Decreases redness, swelling and the number of pimples caused by rosacea and acne.", classes: ["Antibiotics"]},
  {id: 20, name: "Niacinamide", minimum_percentage: "2.0", maximum_percentage: "4.0", description: "Vitamin B3- improves inflammation, hydrates skin, and helps prevent skin cancer.", classes: ["Anti-Inflammatories", "Anti-Carcinogens"]},
  {id: 41, name: "Oxymetazoline", minimum_percentage: "0.5", maximum_percentage: "2.0", description: "Stops over-dilation of blood vessels, reducing swelling and redness.", classes: ["Vasoconstrictors"]},
  
  {id: 25, name: "Sodium Sulfacetamide", minimum_percentage: "2.5", maximum_percentage: "10.0", description: "A potent anti-inflammatory and also reduces bacterial growth.", classes: ["Anti-Microbials", "Anti-Inflammatories"]},
  {id: 22, name: "Spironolactone", minimum_percentage: "2.0", maximum_percentage: "5.0", description: "Effective in the treatment of hormonal acne.", classes: ["Hormonal Modulators"]},
  {id: 27, name: "Tacrolimus", minimum_percentage: "0.03", maximum_percentage: "0.1", description: "A potent non-steroidal anti-inflammatory.", classes: ["Anti-Inflammatories"]},
  {id: 39, name: "Triamcinolone", minimum_percentage: "0.025", maximum_percentage: "2.0", description: "A mid-strength anti-inflammatory steroid.", classes: ["Steroid"]},
  {id: 33, name: "Urea", minimum_percentage: "1.0", maximum_percentage: "5.0", description: "Created when the body breaks down proteins, helps to maintain skin hydration and pH balance.", classes: ["Humectant"]},
  {id: 24, name: "Zinc Oxide", minimum_percentage: "5.0", maximum_percentage: "10.0", description: "", classes: ["Barriers"]},
  {id: 28, name: "Palmitoyl Pentapeptide-4", minimum_percentage: "1.0", maximum_percentage: "5.0", description: "A messenger peptide that tells cells to produce a stronger matrix (more collagen).", classes: ["Collagenesis Upregulator"]},
  {id: 21, name: "Retinol", minimum_percentage: "0.1", maximum_percentage: "3.0", description: "Vitamin A derivative. Important for skin cancer prevention, thickening of the epidermis, regulation of oil glands, collagen synthesis, and exfoliating dead skin cells. Less aggressive than other retinoids such as tretinoin.", classes: ["Retinoids"]},
  {id: 23, name: "Sulfur", minimum_percentage: "2.0", maximum_percentage: "4.0", description: "A potent anti-inflammatory and also reduces bacterial growth.", classes: ["Anti-Inflammatories"]},
  {id: 26, name: "Tretinoin", minimum_percentage: "0.01", maximum_percentage: "0.1", description: "Vitamin A derivative. Important for skin cancer prevention, thickening of the epidermis, regulation of oil glands, collagen synthesis, and exfoliating dead skin cells.", classes: ["Retinoids", "Anti-Carcinogens"]},
  {id: 38, name: "Vitamin K1", minimum_percentage: "0.25", maximum_percentage: "1.0", description: "Active Vitamin K, an essential co-factor for blood clotting.", classes: ["Anti-Ecchymotic"]}
])
